

#pragma once

#ifndef GO_MOC_46aa22_H
#define GO_MOC_46aa22_H

#include <stdint.h>

#ifdef __cplusplus
class MediaListPage46aa22;
void MediaListPage46aa22_MediaListPage46aa22_QRegisterMetaTypes();
class MediaListTable46aa22;
void MediaListTable46aa22_MediaListTable46aa22_QRegisterMetaTypes();
class MediaListTabs46aa22;
void MediaListTabs46aa22_MediaListTabs46aa22_QRegisterMetaTypes();
class MenuBar46aa22;
void MenuBar46aa22_MenuBar46aa22_QRegisterMetaTypes();
class Navigation46aa22;
void Navigation46aa22_Navigation46aa22_QRegisterMetaTypes();
class SettingsDialog46aa22;
void SettingsDialog46aa22_SettingsDialog46aa22_QRegisterMetaTypes();
class CurrentMediaPage46aa22;
void CurrentMediaPage46aa22_CurrentMediaPage46aa22_QRegisterMetaTypes();
class MainWindow46aa22;
void MainWindow46aa22_MainWindow46aa22_QRegisterMetaTypes();
extern "C" {
#endif

struct Moc_PackedString { char* data; long long len; };
struct Moc_PackedList { void* data; long long len; };
int SettingsDialog46aa22_SettingsDialog46aa22_QRegisterMetaType();
int SettingsDialog46aa22_SettingsDialog46aa22_QRegisterMetaType2(char* typeName);
int SettingsDialog46aa22_SettingsDialog46aa22_QmlRegisterType();
int SettingsDialog46aa22_SettingsDialog46aa22_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* SettingsDialog46aa22___addActions_actions_atList(void* ptr, int i);
void SettingsDialog46aa22___addActions_actions_setList(void* ptr, void* i);
void* SettingsDialog46aa22___addActions_actions_newList(void* ptr);
void* SettingsDialog46aa22___insertActions_actions_atList(void* ptr, int i);
void SettingsDialog46aa22___insertActions_actions_setList(void* ptr, void* i);
void* SettingsDialog46aa22___insertActions_actions_newList(void* ptr);
void* SettingsDialog46aa22___actions_atList(void* ptr, int i);
void SettingsDialog46aa22___actions_setList(void* ptr, void* i);
void* SettingsDialog46aa22___actions_newList(void* ptr);
void* SettingsDialog46aa22___dynamicPropertyNames_atList(void* ptr, int i);
void SettingsDialog46aa22___dynamicPropertyNames_setList(void* ptr, void* i);
void* SettingsDialog46aa22___dynamicPropertyNames_newList(void* ptr);
void* SettingsDialog46aa22___findChildren_atList2(void* ptr, int i);
void SettingsDialog46aa22___findChildren_setList2(void* ptr, void* i);
void* SettingsDialog46aa22___findChildren_newList2(void* ptr);
void* SettingsDialog46aa22___findChildren_atList3(void* ptr, int i);
void SettingsDialog46aa22___findChildren_setList3(void* ptr, void* i);
void* SettingsDialog46aa22___findChildren_newList3(void* ptr);
void* SettingsDialog46aa22___findChildren_atList(void* ptr, int i);
void SettingsDialog46aa22___findChildren_setList(void* ptr, void* i);
void* SettingsDialog46aa22___findChildren_newList(void* ptr);
void* SettingsDialog46aa22___children_atList(void* ptr, int i);
void SettingsDialog46aa22___children_setList(void* ptr, void* i);
void* SettingsDialog46aa22___children_newList(void* ptr);
void* SettingsDialog46aa22_NewSettingsDialog(void* parent, long long ff);
void SettingsDialog46aa22_DestroySettingsDialog(void* ptr);
void SettingsDialog46aa22_DestroySettingsDialogDefault(void* ptr);
char SettingsDialog46aa22_EventFilterDefault(void* ptr, void* o, void* e);
int SettingsDialog46aa22_ExecDefault(void* ptr);
void SettingsDialog46aa22_AcceptDefault(void* ptr);
void SettingsDialog46aa22_CloseEventDefault(void* ptr, void* e);
void SettingsDialog46aa22_ContextMenuEventDefault(void* ptr, void* e);
void SettingsDialog46aa22_DoneDefault(void* ptr, int r);
void SettingsDialog46aa22_KeyPressEventDefault(void* ptr, void* e);
void SettingsDialog46aa22_OpenDefault(void* ptr);
void SettingsDialog46aa22_RejectDefault(void* ptr);
void SettingsDialog46aa22_ResizeEventDefault(void* ptr, void* vqr);
void SettingsDialog46aa22_SetVisibleDefault(void* ptr, char visible);
void SettingsDialog46aa22_ShowEventDefault(void* ptr, void* event);
void* SettingsDialog46aa22_MinimumSizeHintDefault(void* ptr);
void* SettingsDialog46aa22_SizeHintDefault(void* ptr);
;
char SettingsDialog46aa22_CloseDefault(void* ptr);
char SettingsDialog46aa22_EventDefault(void* ptr, void* event);
char SettingsDialog46aa22_FocusNextPrevChildDefault(void* ptr, char next);
char SettingsDialog46aa22_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void SettingsDialog46aa22_ActionEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_ChangeEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_DragEnterEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_DragLeaveEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_DragMoveEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_DropEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_EnterEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_FocusInEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_FocusOutEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_HideDefault(void* ptr);
void SettingsDialog46aa22_HideEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_InputMethodEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_KeyReleaseEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_LeaveEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_LowerDefault(void* ptr);
void SettingsDialog46aa22_MouseDoubleClickEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_MouseMoveEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_MousePressEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_MouseReleaseEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_MoveEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_PaintEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_RaiseDefault(void* ptr);
void SettingsDialog46aa22_RepaintDefault(void* ptr);
void SettingsDialog46aa22_SetDisabledDefault(void* ptr, char disable);
void SettingsDialog46aa22_SetEnabledDefault(void* ptr, char vbo);
void SettingsDialog46aa22_SetFocus2Default(void* ptr);
void SettingsDialog46aa22_SetHiddenDefault(void* ptr, char hidden);
void SettingsDialog46aa22_SetStyleSheetDefault(void* ptr, struct Moc_PackedString styleSheet);
void SettingsDialog46aa22_SetWindowModifiedDefault(void* ptr, char vbo);
void SettingsDialog46aa22_SetWindowTitleDefault(void* ptr, struct Moc_PackedString vqs);
void SettingsDialog46aa22_ShowDefault(void* ptr);
void SettingsDialog46aa22_ShowFullScreenDefault(void* ptr);
void SettingsDialog46aa22_ShowMaximizedDefault(void* ptr);
void SettingsDialog46aa22_ShowMinimizedDefault(void* ptr);
void SettingsDialog46aa22_ShowNormalDefault(void* ptr);
void SettingsDialog46aa22_TabletEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_UpdateDefault(void* ptr);
void SettingsDialog46aa22_UpdateMicroFocusDefault(void* ptr);
void SettingsDialog46aa22_WheelEventDefault(void* ptr, void* event);
void* SettingsDialog46aa22_PaintEngineDefault(void* ptr);
void* SettingsDialog46aa22_InputMethodQueryDefault(void* ptr, long long query);
char SettingsDialog46aa22_HasHeightForWidthDefault(void* ptr);
int SettingsDialog46aa22_HeightForWidthDefault(void* ptr, int w);
int SettingsDialog46aa22_MetricDefault(void* ptr, long long m);
void SettingsDialog46aa22_InitPainterDefault(void* ptr, void* painter);
void SettingsDialog46aa22_ChildEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_ConnectNotifyDefault(void* ptr, void* sign);
void SettingsDialog46aa22_CustomEventDefault(void* ptr, void* event);
void SettingsDialog46aa22_DeleteLaterDefault(void* ptr);
void SettingsDialog46aa22_DisconnectNotifyDefault(void* ptr, void* sign);
void SettingsDialog46aa22_TimerEventDefault(void* ptr, void* event);
int CurrentMediaPage46aa22_CurrentMediaPage46aa22_QRegisterMetaType();
int CurrentMediaPage46aa22_CurrentMediaPage46aa22_QRegisterMetaType2(char* typeName);
int CurrentMediaPage46aa22_CurrentMediaPage46aa22_QmlRegisterType();
int CurrentMediaPage46aa22_CurrentMediaPage46aa22_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* CurrentMediaPage46aa22___addActions_actions_atList(void* ptr, int i);
void CurrentMediaPage46aa22___addActions_actions_setList(void* ptr, void* i);
void* CurrentMediaPage46aa22___addActions_actions_newList(void* ptr);
void* CurrentMediaPage46aa22___insertActions_actions_atList(void* ptr, int i);
void CurrentMediaPage46aa22___insertActions_actions_setList(void* ptr, void* i);
void* CurrentMediaPage46aa22___insertActions_actions_newList(void* ptr);
void* CurrentMediaPage46aa22___actions_atList(void* ptr, int i);
void CurrentMediaPage46aa22___actions_setList(void* ptr, void* i);
void* CurrentMediaPage46aa22___actions_newList(void* ptr);
void* CurrentMediaPage46aa22___dynamicPropertyNames_atList(void* ptr, int i);
void CurrentMediaPage46aa22___dynamicPropertyNames_setList(void* ptr, void* i);
void* CurrentMediaPage46aa22___dynamicPropertyNames_newList(void* ptr);
void* CurrentMediaPage46aa22___findChildren_atList2(void* ptr, int i);
void CurrentMediaPage46aa22___findChildren_setList2(void* ptr, void* i);
void* CurrentMediaPage46aa22___findChildren_newList2(void* ptr);
void* CurrentMediaPage46aa22___findChildren_atList3(void* ptr, int i);
void CurrentMediaPage46aa22___findChildren_setList3(void* ptr, void* i);
void* CurrentMediaPage46aa22___findChildren_newList3(void* ptr);
void* CurrentMediaPage46aa22___findChildren_atList(void* ptr, int i);
void CurrentMediaPage46aa22___findChildren_setList(void* ptr, void* i);
void* CurrentMediaPage46aa22___findChildren_newList(void* ptr);
void* CurrentMediaPage46aa22___children_atList(void* ptr, int i);
void CurrentMediaPage46aa22___children_setList(void* ptr, void* i);
void* CurrentMediaPage46aa22___children_newList(void* ptr);
void* CurrentMediaPage46aa22_NewCurrentMediaPage(void* parent);
void CurrentMediaPage46aa22_DestroyCurrentMediaPage(void* ptr);
void CurrentMediaPage46aa22_DestroyCurrentMediaPageDefault(void* ptr);
char CurrentMediaPage46aa22_EventDefault(void* ptr, void* ev);
void CurrentMediaPage46aa22_ChangeEventDefault(void* ptr, void* ev);
void CurrentMediaPage46aa22_KeyPressEventDefault(void* ptr, void* e);
void CurrentMediaPage46aa22_PaintEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_ResizeEventDefault(void* ptr, void* e);
void CurrentMediaPage46aa22_SetCurrentIndexDefault(void* ptr, int index);
void CurrentMediaPage46aa22_SetCurrentWidgetDefault(void* ptr, void* widget);
void CurrentMediaPage46aa22_ShowEventDefault(void* ptr, void* vqs);
void CurrentMediaPage46aa22_TabInsertedDefault(void* ptr, int index);
void CurrentMediaPage46aa22_TabRemovedDefault(void* ptr, int index);
void* CurrentMediaPage46aa22_MinimumSizeHintDefault(void* ptr);
void* CurrentMediaPage46aa22_SizeHintDefault(void* ptr);
char CurrentMediaPage46aa22_HasHeightForWidthDefault(void* ptr);
;
int CurrentMediaPage46aa22_HeightForWidthDefault(void* ptr, int width);
char CurrentMediaPage46aa22_CloseDefault(void* ptr);
char CurrentMediaPage46aa22_FocusNextPrevChildDefault(void* ptr, char next);
char CurrentMediaPage46aa22_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void CurrentMediaPage46aa22_ActionEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_CloseEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_ContextMenuEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_DragEnterEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_DragLeaveEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_DragMoveEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_DropEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_EnterEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_FocusInEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_FocusOutEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_HideDefault(void* ptr);
void CurrentMediaPage46aa22_HideEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_InputMethodEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_KeyReleaseEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_LeaveEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_LowerDefault(void* ptr);
void CurrentMediaPage46aa22_MouseDoubleClickEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_MouseMoveEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_MousePressEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_MouseReleaseEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_MoveEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_RaiseDefault(void* ptr);
void CurrentMediaPage46aa22_RepaintDefault(void* ptr);
void CurrentMediaPage46aa22_SetDisabledDefault(void* ptr, char disable);
void CurrentMediaPage46aa22_SetEnabledDefault(void* ptr, char vbo);
void CurrentMediaPage46aa22_SetFocus2Default(void* ptr);
void CurrentMediaPage46aa22_SetHiddenDefault(void* ptr, char hidden);
void CurrentMediaPage46aa22_SetStyleSheetDefault(void* ptr, struct Moc_PackedString styleSheet);
void CurrentMediaPage46aa22_SetVisibleDefault(void* ptr, char visible);
void CurrentMediaPage46aa22_SetWindowModifiedDefault(void* ptr, char vbo);
void CurrentMediaPage46aa22_SetWindowTitleDefault(void* ptr, struct Moc_PackedString vqs);
void CurrentMediaPage46aa22_ShowDefault(void* ptr);
void CurrentMediaPage46aa22_ShowFullScreenDefault(void* ptr);
void CurrentMediaPage46aa22_ShowMaximizedDefault(void* ptr);
void CurrentMediaPage46aa22_ShowMinimizedDefault(void* ptr);
void CurrentMediaPage46aa22_ShowNormalDefault(void* ptr);
void CurrentMediaPage46aa22_TabletEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_UpdateDefault(void* ptr);
void CurrentMediaPage46aa22_UpdateMicroFocusDefault(void* ptr);
void CurrentMediaPage46aa22_WheelEventDefault(void* ptr, void* event);
void* CurrentMediaPage46aa22_PaintEngineDefault(void* ptr);
void* CurrentMediaPage46aa22_InputMethodQueryDefault(void* ptr, long long query);
int CurrentMediaPage46aa22_MetricDefault(void* ptr, long long m);
void CurrentMediaPage46aa22_InitPainterDefault(void* ptr, void* painter);
char CurrentMediaPage46aa22_EventFilterDefault(void* ptr, void* watched, void* event);
void CurrentMediaPage46aa22_ChildEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_ConnectNotifyDefault(void* ptr, void* sign);
void CurrentMediaPage46aa22_CustomEventDefault(void* ptr, void* event);
void CurrentMediaPage46aa22_DeleteLaterDefault(void* ptr);
void CurrentMediaPage46aa22_DisconnectNotifyDefault(void* ptr, void* sign);
void CurrentMediaPage46aa22_TimerEventDefault(void* ptr, void* event);
int MainWindow46aa22_MainWindow46aa22_QRegisterMetaType();
int MainWindow46aa22_MainWindow46aa22_QRegisterMetaType2(char* typeName);
int MainWindow46aa22_MainWindow46aa22_QmlRegisterType();
int MainWindow46aa22_MainWindow46aa22_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* MainWindow46aa22___resizeDocks_docks_atList(void* ptr, int i);
void MainWindow46aa22___resizeDocks_docks_setList(void* ptr, void* i);
void* MainWindow46aa22___resizeDocks_docks_newList(void* ptr);
int MainWindow46aa22___resizeDocks_sizes_atList(void* ptr, int i);
void MainWindow46aa22___resizeDocks_sizes_setList(void* ptr, int i);
void* MainWindow46aa22___resizeDocks_sizes_newList(void* ptr);
void* MainWindow46aa22___tabifiedDockWidgets_atList(void* ptr, int i);
void MainWindow46aa22___tabifiedDockWidgets_setList(void* ptr, void* i);
void* MainWindow46aa22___tabifiedDockWidgets_newList(void* ptr);
void* MainWindow46aa22___addActions_actions_atList(void* ptr, int i);
void MainWindow46aa22___addActions_actions_setList(void* ptr, void* i);
void* MainWindow46aa22___addActions_actions_newList(void* ptr);
void* MainWindow46aa22___insertActions_actions_atList(void* ptr, int i);
void MainWindow46aa22___insertActions_actions_setList(void* ptr, void* i);
void* MainWindow46aa22___insertActions_actions_newList(void* ptr);
void* MainWindow46aa22___actions_atList(void* ptr, int i);
void MainWindow46aa22___actions_setList(void* ptr, void* i);
void* MainWindow46aa22___actions_newList(void* ptr);
void* MainWindow46aa22___dynamicPropertyNames_atList(void* ptr, int i);
void MainWindow46aa22___dynamicPropertyNames_setList(void* ptr, void* i);
void* MainWindow46aa22___dynamicPropertyNames_newList(void* ptr);
void* MainWindow46aa22___findChildren_atList2(void* ptr, int i);
void MainWindow46aa22___findChildren_setList2(void* ptr, void* i);
void* MainWindow46aa22___findChildren_newList2(void* ptr);
void* MainWindow46aa22___findChildren_atList3(void* ptr, int i);
void MainWindow46aa22___findChildren_setList3(void* ptr, void* i);
void* MainWindow46aa22___findChildren_newList3(void* ptr);
void* MainWindow46aa22___findChildren_atList(void* ptr, int i);
void MainWindow46aa22___findChildren_setList(void* ptr, void* i);
void* MainWindow46aa22___findChildren_newList(void* ptr);
void* MainWindow46aa22___children_atList(void* ptr, int i);
void MainWindow46aa22___children_setList(void* ptr, void* i);
void* MainWindow46aa22___children_newList(void* ptr);
void* MainWindow46aa22_NewMainWindow(void* parent, long long flags);
void MainWindow46aa22_DestroyMainWindow(void* ptr);
void MainWindow46aa22_DestroyMainWindowDefault(void* ptr);
void* MainWindow46aa22_CreatePopupMenuDefault(void* ptr);
char MainWindow46aa22_EventDefault(void* ptr, void* event);
void MainWindow46aa22_ContextMenuEventDefault(void* ptr, void* event);
void MainWindow46aa22_SetAnimatedDefault(void* ptr, char enabled);
void MainWindow46aa22_SetDockNestingEnabledDefault(void* ptr, char enabled);
void MainWindow46aa22_SetUnifiedTitleAndToolBarOnMacDefault(void* ptr, char set);
;
char MainWindow46aa22_CloseDefault(void* ptr);
char MainWindow46aa22_FocusNextPrevChildDefault(void* ptr, char next);
char MainWindow46aa22_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void MainWindow46aa22_ActionEventDefault(void* ptr, void* event);
void MainWindow46aa22_ChangeEventDefault(void* ptr, void* event);
void MainWindow46aa22_CloseEventDefault(void* ptr, void* event);
void MainWindow46aa22_DragEnterEventDefault(void* ptr, void* event);
void MainWindow46aa22_DragLeaveEventDefault(void* ptr, void* event);
void MainWindow46aa22_DragMoveEventDefault(void* ptr, void* event);
void MainWindow46aa22_DropEventDefault(void* ptr, void* event);
void MainWindow46aa22_EnterEventDefault(void* ptr, void* event);
void MainWindow46aa22_FocusInEventDefault(void* ptr, void* event);
void MainWindow46aa22_FocusOutEventDefault(void* ptr, void* event);
void MainWindow46aa22_HideDefault(void* ptr);
void MainWindow46aa22_HideEventDefault(void* ptr, void* event);
void MainWindow46aa22_InputMethodEventDefault(void* ptr, void* event);
void MainWindow46aa22_KeyPressEventDefault(void* ptr, void* event);
void MainWindow46aa22_KeyReleaseEventDefault(void* ptr, void* event);
void MainWindow46aa22_LeaveEventDefault(void* ptr, void* event);
void MainWindow46aa22_LowerDefault(void* ptr);
void MainWindow46aa22_MouseDoubleClickEventDefault(void* ptr, void* event);
void MainWindow46aa22_MouseMoveEventDefault(void* ptr, void* event);
void MainWindow46aa22_MousePressEventDefault(void* ptr, void* event);
void MainWindow46aa22_MouseReleaseEventDefault(void* ptr, void* event);
void MainWindow46aa22_MoveEventDefault(void* ptr, void* event);
void MainWindow46aa22_PaintEventDefault(void* ptr, void* event);
void MainWindow46aa22_RaiseDefault(void* ptr);
void MainWindow46aa22_RepaintDefault(void* ptr);
void MainWindow46aa22_ResizeEventDefault(void* ptr, void* event);
void MainWindow46aa22_SetDisabledDefault(void* ptr, char disable);
void MainWindow46aa22_SetEnabledDefault(void* ptr, char vbo);
void MainWindow46aa22_SetFocus2Default(void* ptr);
void MainWindow46aa22_SetHiddenDefault(void* ptr, char hidden);
void MainWindow46aa22_SetStyleSheetDefault(void* ptr, struct Moc_PackedString styleSheet);
void MainWindow46aa22_SetVisibleDefault(void* ptr, char visible);
void MainWindow46aa22_SetWindowModifiedDefault(void* ptr, char vbo);
void MainWindow46aa22_SetWindowTitleDefault(void* ptr, struct Moc_PackedString vqs);
void MainWindow46aa22_ShowDefault(void* ptr);
void MainWindow46aa22_ShowEventDefault(void* ptr, void* event);
void MainWindow46aa22_ShowFullScreenDefault(void* ptr);
void MainWindow46aa22_ShowMaximizedDefault(void* ptr);
void MainWindow46aa22_ShowMinimizedDefault(void* ptr);
void MainWindow46aa22_ShowNormalDefault(void* ptr);
void MainWindow46aa22_TabletEventDefault(void* ptr, void* event);
void MainWindow46aa22_UpdateDefault(void* ptr);
void MainWindow46aa22_UpdateMicroFocusDefault(void* ptr);
void MainWindow46aa22_WheelEventDefault(void* ptr, void* event);
void* MainWindow46aa22_PaintEngineDefault(void* ptr);
void* MainWindow46aa22_MinimumSizeHintDefault(void* ptr);
void* MainWindow46aa22_SizeHintDefault(void* ptr);
void* MainWindow46aa22_InputMethodQueryDefault(void* ptr, long long query);
char MainWindow46aa22_HasHeightForWidthDefault(void* ptr);
int MainWindow46aa22_HeightForWidthDefault(void* ptr, int w);
int MainWindow46aa22_MetricDefault(void* ptr, long long m);
void MainWindow46aa22_InitPainterDefault(void* ptr, void* painter);
char MainWindow46aa22_EventFilterDefault(void* ptr, void* watched, void* event);
void MainWindow46aa22_ChildEventDefault(void* ptr, void* event);
void MainWindow46aa22_ConnectNotifyDefault(void* ptr, void* sign);
void MainWindow46aa22_CustomEventDefault(void* ptr, void* event);
void MainWindow46aa22_DeleteLaterDefault(void* ptr);
void MainWindow46aa22_DisconnectNotifyDefault(void* ptr, void* sign);
void MainWindow46aa22_TimerEventDefault(void* ptr, void* event);
int MediaListPage46aa22_MediaListPage46aa22_QRegisterMetaType();
int MediaListPage46aa22_MediaListPage46aa22_QRegisterMetaType2(char* typeName);
int MediaListPage46aa22_MediaListPage46aa22_QmlRegisterType();
int MediaListPage46aa22_MediaListPage46aa22_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* MediaListPage46aa22___addActions_actions_atList(void* ptr, int i);
void MediaListPage46aa22___addActions_actions_setList(void* ptr, void* i);
void* MediaListPage46aa22___addActions_actions_newList(void* ptr);
void* MediaListPage46aa22___insertActions_actions_atList(void* ptr, int i);
void MediaListPage46aa22___insertActions_actions_setList(void* ptr, void* i);
void* MediaListPage46aa22___insertActions_actions_newList(void* ptr);
void* MediaListPage46aa22___actions_atList(void* ptr, int i);
void MediaListPage46aa22___actions_setList(void* ptr, void* i);
void* MediaListPage46aa22___actions_newList(void* ptr);
void* MediaListPage46aa22___dynamicPropertyNames_atList(void* ptr, int i);
void MediaListPage46aa22___dynamicPropertyNames_setList(void* ptr, void* i);
void* MediaListPage46aa22___dynamicPropertyNames_newList(void* ptr);
void* MediaListPage46aa22___findChildren_atList2(void* ptr, int i);
void MediaListPage46aa22___findChildren_setList2(void* ptr, void* i);
void* MediaListPage46aa22___findChildren_newList2(void* ptr);
void* MediaListPage46aa22___findChildren_atList3(void* ptr, int i);
void MediaListPage46aa22___findChildren_setList3(void* ptr, void* i);
void* MediaListPage46aa22___findChildren_newList3(void* ptr);
void* MediaListPage46aa22___findChildren_atList(void* ptr, int i);
void MediaListPage46aa22___findChildren_setList(void* ptr, void* i);
void* MediaListPage46aa22___findChildren_newList(void* ptr);
void* MediaListPage46aa22___children_atList(void* ptr, int i);
void MediaListPage46aa22___children_setList(void* ptr, void* i);
void* MediaListPage46aa22___children_newList(void* ptr);
void* MediaListPage46aa22_NewMediaListPage(void* parent, long long ff);
void MediaListPage46aa22_DestroyMediaListPage(void* ptr);
void MediaListPage46aa22_DestroyMediaListPageDefault(void* ptr);
char MediaListPage46aa22_CloseDefault(void* ptr);
char MediaListPage46aa22_EventDefault(void* ptr, void* event);
char MediaListPage46aa22_FocusNextPrevChildDefault(void* ptr, char next);
char MediaListPage46aa22_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void MediaListPage46aa22_ActionEventDefault(void* ptr, void* event);
void MediaListPage46aa22_ChangeEventDefault(void* ptr, void* event);
void MediaListPage46aa22_CloseEventDefault(void* ptr, void* event);
void MediaListPage46aa22_ContextMenuEventDefault(void* ptr, void* event);
void MediaListPage46aa22_DragEnterEventDefault(void* ptr, void* event);
void MediaListPage46aa22_DragLeaveEventDefault(void* ptr, void* event);
void MediaListPage46aa22_DragMoveEventDefault(void* ptr, void* event);
void MediaListPage46aa22_DropEventDefault(void* ptr, void* event);
void MediaListPage46aa22_EnterEventDefault(void* ptr, void* event);
void MediaListPage46aa22_FocusInEventDefault(void* ptr, void* event);
void MediaListPage46aa22_FocusOutEventDefault(void* ptr, void* event);
void MediaListPage46aa22_HideDefault(void* ptr);
void MediaListPage46aa22_HideEventDefault(void* ptr, void* event);
void MediaListPage46aa22_InputMethodEventDefault(void* ptr, void* event);
void MediaListPage46aa22_KeyPressEventDefault(void* ptr, void* event);
void MediaListPage46aa22_KeyReleaseEventDefault(void* ptr, void* event);
void MediaListPage46aa22_LeaveEventDefault(void* ptr, void* event);
void MediaListPage46aa22_LowerDefault(void* ptr);
void MediaListPage46aa22_MouseDoubleClickEventDefault(void* ptr, void* event);
void MediaListPage46aa22_MouseMoveEventDefault(void* ptr, void* event);
void MediaListPage46aa22_MousePressEventDefault(void* ptr, void* event);
void MediaListPage46aa22_MouseReleaseEventDefault(void* ptr, void* event);
void MediaListPage46aa22_MoveEventDefault(void* ptr, void* event);
void MediaListPage46aa22_PaintEventDefault(void* ptr, void* event);
void MediaListPage46aa22_RaiseDefault(void* ptr);
void MediaListPage46aa22_RepaintDefault(void* ptr);
void MediaListPage46aa22_ResizeEventDefault(void* ptr, void* event);
void MediaListPage46aa22_SetDisabledDefault(void* ptr, char disable);
void MediaListPage46aa22_SetEnabledDefault(void* ptr, char vbo);
void MediaListPage46aa22_SetFocus2Default(void* ptr);
void MediaListPage46aa22_SetHiddenDefault(void* ptr, char hidden);
void MediaListPage46aa22_SetStyleSheetDefault(void* ptr, struct Moc_PackedString styleSheet);
void MediaListPage46aa22_SetVisibleDefault(void* ptr, char visible);
void MediaListPage46aa22_SetWindowModifiedDefault(void* ptr, char vbo);
void MediaListPage46aa22_SetWindowTitleDefault(void* ptr, struct Moc_PackedString vqs);
void MediaListPage46aa22_ShowDefault(void* ptr);
void MediaListPage46aa22_ShowEventDefault(void* ptr, void* event);
void MediaListPage46aa22_ShowFullScreenDefault(void* ptr);
void MediaListPage46aa22_ShowMaximizedDefault(void* ptr);
void MediaListPage46aa22_ShowMinimizedDefault(void* ptr);
void MediaListPage46aa22_ShowNormalDefault(void* ptr);
void MediaListPage46aa22_TabletEventDefault(void* ptr, void* event);
void MediaListPage46aa22_UpdateDefault(void* ptr);
void MediaListPage46aa22_UpdateMicroFocusDefault(void* ptr);
void MediaListPage46aa22_WheelEventDefault(void* ptr, void* event);
void* MediaListPage46aa22_PaintEngineDefault(void* ptr);
void* MediaListPage46aa22_MinimumSizeHintDefault(void* ptr);
void* MediaListPage46aa22_SizeHintDefault(void* ptr);
void* MediaListPage46aa22_InputMethodQueryDefault(void* ptr, long long query);
char MediaListPage46aa22_HasHeightForWidthDefault(void* ptr);
;
int MediaListPage46aa22_HeightForWidthDefault(void* ptr, int w);
int MediaListPage46aa22_MetricDefault(void* ptr, long long m);
void MediaListPage46aa22_InitPainterDefault(void* ptr, void* painter);
char MediaListPage46aa22_EventFilterDefault(void* ptr, void* watched, void* event);
void MediaListPage46aa22_ChildEventDefault(void* ptr, void* event);
void MediaListPage46aa22_ConnectNotifyDefault(void* ptr, void* sign);
void MediaListPage46aa22_CustomEventDefault(void* ptr, void* event);
void MediaListPage46aa22_DeleteLaterDefault(void* ptr);
void MediaListPage46aa22_DisconnectNotifyDefault(void* ptr, void* sign);
void MediaListPage46aa22_TimerEventDefault(void* ptr, void* event);
int MediaListTable46aa22_MediaListTable46aa22_QRegisterMetaType();
int MediaListTable46aa22_MediaListTable46aa22_QRegisterMetaType2(char* typeName);
int MediaListTable46aa22_MediaListTable46aa22_QmlRegisterType();
int MediaListTable46aa22_MediaListTable46aa22_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
int MediaListTable46aa22_____setItemData_roles_keyList_atList(void* ptr, int i);
void MediaListTable46aa22_____setItemData_roles_keyList_setList(void* ptr, int i);
void* MediaListTable46aa22_____setItemData_roles_keyList_newList(void* ptr);
int MediaListTable46aa22_____roleNames_keyList_atList(void* ptr, int i);
void MediaListTable46aa22_____roleNames_keyList_setList(void* ptr, int i);
void* MediaListTable46aa22_____roleNames_keyList_newList(void* ptr);
int MediaListTable46aa22_____itemData_keyList_atList(void* ptr, int i);
void MediaListTable46aa22_____itemData_keyList_setList(void* ptr, int i);
void* MediaListTable46aa22_____itemData_keyList_newList(void* ptr);
void* MediaListTable46aa22___setItemData_roles_atList(void* ptr, int v, int i);
void MediaListTable46aa22___setItemData_roles_setList(void* ptr, int key, void* i);
void* MediaListTable46aa22___setItemData_roles_newList(void* ptr);
struct Moc_PackedList MediaListTable46aa22___setItemData_roles_keyList(void* ptr);
void* MediaListTable46aa22___changePersistentIndexList_from_atList(void* ptr, int i);
void MediaListTable46aa22___changePersistentIndexList_from_setList(void* ptr, void* i);
void* MediaListTable46aa22___changePersistentIndexList_from_newList(void* ptr);
void* MediaListTable46aa22___changePersistentIndexList_to_atList(void* ptr, int i);
void MediaListTable46aa22___changePersistentIndexList_to_setList(void* ptr, void* i);
void* MediaListTable46aa22___changePersistentIndexList_to_newList(void* ptr);
int MediaListTable46aa22___dataChanged_roles_atList(void* ptr, int i);
void MediaListTable46aa22___dataChanged_roles_setList(void* ptr, int i);
void* MediaListTable46aa22___dataChanged_roles_newList(void* ptr);
void* MediaListTable46aa22___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void MediaListTable46aa22___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* MediaListTable46aa22___layoutAboutToBeChanged_parents_newList(void* ptr);
void* MediaListTable46aa22___layoutChanged_parents_atList(void* ptr, int i);
void MediaListTable46aa22___layoutChanged_parents_setList(void* ptr, void* i);
void* MediaListTable46aa22___layoutChanged_parents_newList(void* ptr);
void* MediaListTable46aa22___roleNames_atList(void* ptr, int v, int i);
void MediaListTable46aa22___roleNames_setList(void* ptr, int key, void* i);
void* MediaListTable46aa22___roleNames_newList(void* ptr);
struct Moc_PackedList MediaListTable46aa22___roleNames_keyList(void* ptr);
void* MediaListTable46aa22___itemData_atList(void* ptr, int v, int i);
void MediaListTable46aa22___itemData_setList(void* ptr, int key, void* i);
void* MediaListTable46aa22___itemData_newList(void* ptr);
struct Moc_PackedList MediaListTable46aa22___itemData_keyList(void* ptr);
void* MediaListTable46aa22___mimeData_indexes_atList(void* ptr, int i);
void MediaListTable46aa22___mimeData_indexes_setList(void* ptr, void* i);
void* MediaListTable46aa22___mimeData_indexes_newList(void* ptr);
void* MediaListTable46aa22___match_atList(void* ptr, int i);
void MediaListTable46aa22___match_setList(void* ptr, void* i);
void* MediaListTable46aa22___match_newList(void* ptr);
void* MediaListTable46aa22___persistentIndexList_atList(void* ptr, int i);
void MediaListTable46aa22___persistentIndexList_setList(void* ptr, void* i);
void* MediaListTable46aa22___persistentIndexList_newList(void* ptr);
int MediaListTable46aa22_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void MediaListTable46aa22_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* MediaListTable46aa22_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int MediaListTable46aa22_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void MediaListTable46aa22_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* MediaListTable46aa22_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* MediaListTable46aa22___dynamicPropertyNames_atList(void* ptr, int i);
void MediaListTable46aa22___dynamicPropertyNames_setList(void* ptr, void* i);
void* MediaListTable46aa22___dynamicPropertyNames_newList(void* ptr);
void* MediaListTable46aa22___findChildren_atList2(void* ptr, int i);
void MediaListTable46aa22___findChildren_setList2(void* ptr, void* i);
void* MediaListTable46aa22___findChildren_newList2(void* ptr);
void* MediaListTable46aa22___findChildren_atList3(void* ptr, int i);
void MediaListTable46aa22___findChildren_setList3(void* ptr, void* i);
void* MediaListTable46aa22___findChildren_newList3(void* ptr);
void* MediaListTable46aa22___findChildren_atList(void* ptr, int i);
void MediaListTable46aa22___findChildren_setList(void* ptr, void* i);
void* MediaListTable46aa22___findChildren_newList(void* ptr);
void* MediaListTable46aa22___children_atList(void* ptr, int i);
void MediaListTable46aa22___children_setList(void* ptr, void* i);
void* MediaListTable46aa22___children_newList(void* ptr);
void* MediaListTable46aa22_NewMediaListTable(void* parent);
void MediaListTable46aa22_DestroyMediaListTable(void* ptr);
void MediaListTable46aa22_DestroyMediaListTableDefault(void* ptr);
char MediaListTable46aa22_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
void* MediaListTable46aa22_IndexDefault(void* ptr, int row, int column, void* parent);
void* MediaListTable46aa22_SiblingDefault(void* ptr, int row, int column, void* idx);
long long MediaListTable46aa22_FlagsDefault(void* ptr, void* index);
;
char MediaListTable46aa22_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char MediaListTable46aa22_InsertRowsDefault(void* ptr, int row, int count, void* parent);
char MediaListTable46aa22_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char MediaListTable46aa22_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
char MediaListTable46aa22_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char MediaListTable46aa22_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
char MediaListTable46aa22_SetDataDefault(void* ptr, void* index, void* value, int role);
char MediaListTable46aa22_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char MediaListTable46aa22_SetItemDataDefault(void* ptr, void* index, void* roles);
char MediaListTable46aa22_SubmitDefault(void* ptr);
void MediaListTable46aa22_FetchMoreDefault(void* ptr, void* parent);
void MediaListTable46aa22_ResetInternalDataDefault(void* ptr);
void MediaListTable46aa22_RevertDefault(void* ptr);
void MediaListTable46aa22_SortDefault(void* ptr, int column, long long order);
struct Moc_PackedList MediaListTable46aa22_RoleNamesDefault(void* ptr);
struct Moc_PackedList MediaListTable46aa22_ItemDataDefault(void* ptr, void* index);
void* MediaListTable46aa22_MimeDataDefault(void* ptr, void* indexes);
void* MediaListTable46aa22_BuddyDefault(void* ptr, void* index);
void* MediaListTable46aa22_ParentDefault(void* ptr, void* index);
struct Moc_PackedList MediaListTable46aa22_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* MediaListTable46aa22_SpanDefault(void* ptr, void* index);
struct Moc_PackedString MediaListTable46aa22_MimeTypesDefault(void* ptr);
void* MediaListTable46aa22_DataDefault(void* ptr, void* index, int role);
void* MediaListTable46aa22_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
long long MediaListTable46aa22_SupportedDragActionsDefault(void* ptr);
long long MediaListTable46aa22_SupportedDropActionsDefault(void* ptr);
char MediaListTable46aa22_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char MediaListTable46aa22_CanFetchMoreDefault(void* ptr, void* parent);
char MediaListTable46aa22_HasChildrenDefault(void* ptr, void* parent);
int MediaListTable46aa22_ColumnCountDefault(void* ptr, void* parent);
int MediaListTable46aa22_RowCountDefault(void* ptr, void* parent);
char MediaListTable46aa22_EventDefault(void* ptr, void* e);
char MediaListTable46aa22_EventFilterDefault(void* ptr, void* watched, void* event);
void MediaListTable46aa22_ChildEventDefault(void* ptr, void* event);
void MediaListTable46aa22_ConnectNotifyDefault(void* ptr, void* sign);
void MediaListTable46aa22_CustomEventDefault(void* ptr, void* event);
void MediaListTable46aa22_DeleteLaterDefault(void* ptr);
void MediaListTable46aa22_DisconnectNotifyDefault(void* ptr, void* sign);
void MediaListTable46aa22_TimerEventDefault(void* ptr, void* event);
int MediaListTabs46aa22_MediaListTabs46aa22_QRegisterMetaType();
int MediaListTabs46aa22_MediaListTabs46aa22_QRegisterMetaType2(char* typeName);
int MediaListTabs46aa22_MediaListTabs46aa22_QmlRegisterType();
int MediaListTabs46aa22_MediaListTabs46aa22_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* MediaListTabs46aa22___addActions_actions_atList(void* ptr, int i);
void MediaListTabs46aa22___addActions_actions_setList(void* ptr, void* i);
void* MediaListTabs46aa22___addActions_actions_newList(void* ptr);
void* MediaListTabs46aa22___insertActions_actions_atList(void* ptr, int i);
void MediaListTabs46aa22___insertActions_actions_setList(void* ptr, void* i);
void* MediaListTabs46aa22___insertActions_actions_newList(void* ptr);
void* MediaListTabs46aa22___actions_atList(void* ptr, int i);
void MediaListTabs46aa22___actions_setList(void* ptr, void* i);
void* MediaListTabs46aa22___actions_newList(void* ptr);
void* MediaListTabs46aa22___dynamicPropertyNames_atList(void* ptr, int i);
void MediaListTabs46aa22___dynamicPropertyNames_setList(void* ptr, void* i);
void* MediaListTabs46aa22___dynamicPropertyNames_newList(void* ptr);
void* MediaListTabs46aa22___findChildren_atList2(void* ptr, int i);
void MediaListTabs46aa22___findChildren_setList2(void* ptr, void* i);
void* MediaListTabs46aa22___findChildren_newList2(void* ptr);
void* MediaListTabs46aa22___findChildren_atList3(void* ptr, int i);
void MediaListTabs46aa22___findChildren_setList3(void* ptr, void* i);
void* MediaListTabs46aa22___findChildren_newList3(void* ptr);
void* MediaListTabs46aa22___findChildren_atList(void* ptr, int i);
void MediaListTabs46aa22___findChildren_setList(void* ptr, void* i);
void* MediaListTabs46aa22___findChildren_newList(void* ptr);
void* MediaListTabs46aa22___children_atList(void* ptr, int i);
void MediaListTabs46aa22___children_setList(void* ptr, void* i);
void* MediaListTabs46aa22___children_newList(void* ptr);
void* MediaListTabs46aa22_NewMediaListTabs(void* parent);
void MediaListTabs46aa22_DestroyMediaListTabs(void* ptr);
void MediaListTabs46aa22_DestroyMediaListTabsDefault(void* ptr);
char MediaListTabs46aa22_EventDefault(void* ptr, void* ev);
void MediaListTabs46aa22_ChangeEventDefault(void* ptr, void* ev);
void MediaListTabs46aa22_KeyPressEventDefault(void* ptr, void* e);
void MediaListTabs46aa22_PaintEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_ResizeEventDefault(void* ptr, void* e);
void MediaListTabs46aa22_SetCurrentIndexDefault(void* ptr, int index);
void MediaListTabs46aa22_SetCurrentWidgetDefault(void* ptr, void* widget);
void MediaListTabs46aa22_ShowEventDefault(void* ptr, void* vqs);
void MediaListTabs46aa22_TabInsertedDefault(void* ptr, int index);
void MediaListTabs46aa22_TabRemovedDefault(void* ptr, int index);
void* MediaListTabs46aa22_MinimumSizeHintDefault(void* ptr);
void* MediaListTabs46aa22_SizeHintDefault(void* ptr);
char MediaListTabs46aa22_HasHeightForWidthDefault(void* ptr);
;
int MediaListTabs46aa22_HeightForWidthDefault(void* ptr, int width);
char MediaListTabs46aa22_CloseDefault(void* ptr);
char MediaListTabs46aa22_FocusNextPrevChildDefault(void* ptr, char next);
char MediaListTabs46aa22_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void MediaListTabs46aa22_ActionEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_CloseEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_ContextMenuEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_DragEnterEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_DragLeaveEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_DragMoveEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_DropEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_EnterEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_FocusInEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_FocusOutEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_HideDefault(void* ptr);
void MediaListTabs46aa22_HideEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_InputMethodEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_KeyReleaseEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_LeaveEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_LowerDefault(void* ptr);
void MediaListTabs46aa22_MouseDoubleClickEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_MouseMoveEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_MousePressEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_MouseReleaseEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_MoveEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_RaiseDefault(void* ptr);
void MediaListTabs46aa22_RepaintDefault(void* ptr);
void MediaListTabs46aa22_SetDisabledDefault(void* ptr, char disable);
void MediaListTabs46aa22_SetEnabledDefault(void* ptr, char vbo);
void MediaListTabs46aa22_SetFocus2Default(void* ptr);
void MediaListTabs46aa22_SetHiddenDefault(void* ptr, char hidden);
void MediaListTabs46aa22_SetStyleSheetDefault(void* ptr, struct Moc_PackedString styleSheet);
void MediaListTabs46aa22_SetVisibleDefault(void* ptr, char visible);
void MediaListTabs46aa22_SetWindowModifiedDefault(void* ptr, char vbo);
void MediaListTabs46aa22_SetWindowTitleDefault(void* ptr, struct Moc_PackedString vqs);
void MediaListTabs46aa22_ShowDefault(void* ptr);
void MediaListTabs46aa22_ShowFullScreenDefault(void* ptr);
void MediaListTabs46aa22_ShowMaximizedDefault(void* ptr);
void MediaListTabs46aa22_ShowMinimizedDefault(void* ptr);
void MediaListTabs46aa22_ShowNormalDefault(void* ptr);
void MediaListTabs46aa22_TabletEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_UpdateDefault(void* ptr);
void MediaListTabs46aa22_UpdateMicroFocusDefault(void* ptr);
void MediaListTabs46aa22_WheelEventDefault(void* ptr, void* event);
void* MediaListTabs46aa22_PaintEngineDefault(void* ptr);
void* MediaListTabs46aa22_InputMethodQueryDefault(void* ptr, long long query);
int MediaListTabs46aa22_MetricDefault(void* ptr, long long m);
void MediaListTabs46aa22_InitPainterDefault(void* ptr, void* painter);
char MediaListTabs46aa22_EventFilterDefault(void* ptr, void* watched, void* event);
void MediaListTabs46aa22_ChildEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_ConnectNotifyDefault(void* ptr, void* sign);
void MediaListTabs46aa22_CustomEventDefault(void* ptr, void* event);
void MediaListTabs46aa22_DeleteLaterDefault(void* ptr);
void MediaListTabs46aa22_DisconnectNotifyDefault(void* ptr, void* sign);
void MediaListTabs46aa22_TimerEventDefault(void* ptr, void* event);
int MenuBar46aa22_MenuBar46aa22_QRegisterMetaType();
int MenuBar46aa22_MenuBar46aa22_QRegisterMetaType2(char* typeName);
int MenuBar46aa22_MenuBar46aa22_QmlRegisterType();
int MenuBar46aa22_MenuBar46aa22_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* MenuBar46aa22___addActions_actions_atList(void* ptr, int i);
void MenuBar46aa22___addActions_actions_setList(void* ptr, void* i);
void* MenuBar46aa22___addActions_actions_newList(void* ptr);
void* MenuBar46aa22___insertActions_actions_atList(void* ptr, int i);
void MenuBar46aa22___insertActions_actions_setList(void* ptr, void* i);
void* MenuBar46aa22___insertActions_actions_newList(void* ptr);
void* MenuBar46aa22___actions_atList(void* ptr, int i);
void MenuBar46aa22___actions_setList(void* ptr, void* i);
void* MenuBar46aa22___actions_newList(void* ptr);
void* MenuBar46aa22___dynamicPropertyNames_atList(void* ptr, int i);
void MenuBar46aa22___dynamicPropertyNames_setList(void* ptr, void* i);
void* MenuBar46aa22___dynamicPropertyNames_newList(void* ptr);
void* MenuBar46aa22___findChildren_atList2(void* ptr, int i);
void MenuBar46aa22___findChildren_setList2(void* ptr, void* i);
void* MenuBar46aa22___findChildren_newList2(void* ptr);
void* MenuBar46aa22___findChildren_atList3(void* ptr, int i);
void MenuBar46aa22___findChildren_setList3(void* ptr, void* i);
void* MenuBar46aa22___findChildren_newList3(void* ptr);
void* MenuBar46aa22___findChildren_atList(void* ptr, int i);
void MenuBar46aa22___findChildren_setList(void* ptr, void* i);
void* MenuBar46aa22___findChildren_newList(void* ptr);
void* MenuBar46aa22___children_atList(void* ptr, int i);
void MenuBar46aa22___children_setList(void* ptr, void* i);
void* MenuBar46aa22___children_newList(void* ptr);
void* MenuBar46aa22_NewMenuBar(void* parent);
void MenuBar46aa22_DestroyMenuBar(void* ptr);
void MenuBar46aa22_DestroyMenuBarDefault(void* ptr);
char MenuBar46aa22_EventDefault(void* ptr, void* e);
char MenuBar46aa22_EventFilterDefault(void* ptr, void* object, void* event);
void MenuBar46aa22_ActionEventDefault(void* ptr, void* e);
void MenuBar46aa22_ChangeEventDefault(void* ptr, void* e);
void MenuBar46aa22_FocusInEventDefault(void* ptr, void* vqf);
void MenuBar46aa22_FocusOutEventDefault(void* ptr, void* vqf);
void MenuBar46aa22_KeyPressEventDefault(void* ptr, void* e);
void MenuBar46aa22_LeaveEventDefault(void* ptr, void* vqe);
void MenuBar46aa22_MouseMoveEventDefault(void* ptr, void* e);
void MenuBar46aa22_MousePressEventDefault(void* ptr, void* e);
void MenuBar46aa22_MouseReleaseEventDefault(void* ptr, void* e);
void MenuBar46aa22_PaintEventDefault(void* ptr, void* e);
void MenuBar46aa22_ResizeEventDefault(void* ptr, void* vqr);
void MenuBar46aa22_SetVisibleDefault(void* ptr, char visible);
void MenuBar46aa22_TimerEventDefault(void* ptr, void* e);
void* MenuBar46aa22_MinimumSizeHintDefault(void* ptr);
void* MenuBar46aa22_SizeHintDefault(void* ptr);
;
int MenuBar46aa22_HeightForWidthDefault(void* ptr, int vin);
char MenuBar46aa22_CloseDefault(void* ptr);
char MenuBar46aa22_FocusNextPrevChildDefault(void* ptr, char next);
char MenuBar46aa22_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void MenuBar46aa22_CloseEventDefault(void* ptr, void* event);
void MenuBar46aa22_ContextMenuEventDefault(void* ptr, void* event);
void MenuBar46aa22_DragEnterEventDefault(void* ptr, void* event);
void MenuBar46aa22_DragLeaveEventDefault(void* ptr, void* event);
void MenuBar46aa22_DragMoveEventDefault(void* ptr, void* event);
void MenuBar46aa22_DropEventDefault(void* ptr, void* event);
void MenuBar46aa22_EnterEventDefault(void* ptr, void* event);
void MenuBar46aa22_HideDefault(void* ptr);
void MenuBar46aa22_HideEventDefault(void* ptr, void* event);
void MenuBar46aa22_InputMethodEventDefault(void* ptr, void* event);
void MenuBar46aa22_KeyReleaseEventDefault(void* ptr, void* event);
void MenuBar46aa22_LowerDefault(void* ptr);
void MenuBar46aa22_MouseDoubleClickEventDefault(void* ptr, void* event);
void MenuBar46aa22_MoveEventDefault(void* ptr, void* event);
void MenuBar46aa22_RaiseDefault(void* ptr);
void MenuBar46aa22_RepaintDefault(void* ptr);
void MenuBar46aa22_SetDisabledDefault(void* ptr, char disable);
void MenuBar46aa22_SetEnabledDefault(void* ptr, char vbo);
void MenuBar46aa22_SetFocus2Default(void* ptr);
void MenuBar46aa22_SetHiddenDefault(void* ptr, char hidden);
void MenuBar46aa22_SetStyleSheetDefault(void* ptr, struct Moc_PackedString styleSheet);
void MenuBar46aa22_SetWindowModifiedDefault(void* ptr, char vbo);
void MenuBar46aa22_SetWindowTitleDefault(void* ptr, struct Moc_PackedString vqs);
void MenuBar46aa22_ShowDefault(void* ptr);
void MenuBar46aa22_ShowEventDefault(void* ptr, void* event);
void MenuBar46aa22_ShowFullScreenDefault(void* ptr);
void MenuBar46aa22_ShowMaximizedDefault(void* ptr);
void MenuBar46aa22_ShowMinimizedDefault(void* ptr);
void MenuBar46aa22_ShowNormalDefault(void* ptr);
void MenuBar46aa22_TabletEventDefault(void* ptr, void* event);
void MenuBar46aa22_UpdateDefault(void* ptr);
void MenuBar46aa22_UpdateMicroFocusDefault(void* ptr);
void MenuBar46aa22_WheelEventDefault(void* ptr, void* event);
void* MenuBar46aa22_PaintEngineDefault(void* ptr);
void* MenuBar46aa22_InputMethodQueryDefault(void* ptr, long long query);
char MenuBar46aa22_HasHeightForWidthDefault(void* ptr);
int MenuBar46aa22_MetricDefault(void* ptr, long long m);
void MenuBar46aa22_InitPainterDefault(void* ptr, void* painter);
void MenuBar46aa22_ChildEventDefault(void* ptr, void* event);
void MenuBar46aa22_ConnectNotifyDefault(void* ptr, void* sign);
void MenuBar46aa22_CustomEventDefault(void* ptr, void* event);
void MenuBar46aa22_DeleteLaterDefault(void* ptr);
void MenuBar46aa22_DisconnectNotifyDefault(void* ptr, void* sign);
int Navigation46aa22_Navigation46aa22_QRegisterMetaType();
int Navigation46aa22_Navigation46aa22_QRegisterMetaType2(char* typeName);
int Navigation46aa22_Navigation46aa22_QmlRegisterType();
int Navigation46aa22_Navigation46aa22_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* Navigation46aa22___addActions_actions_atList(void* ptr, int i);
void Navigation46aa22___addActions_actions_setList(void* ptr, void* i);
void* Navigation46aa22___addActions_actions_newList(void* ptr);
void* Navigation46aa22___insertActions_actions_atList(void* ptr, int i);
void Navigation46aa22___insertActions_actions_setList(void* ptr, void* i);
void* Navigation46aa22___insertActions_actions_newList(void* ptr);
void* Navigation46aa22___actions_atList(void* ptr, int i);
void Navigation46aa22___actions_setList(void* ptr, void* i);
void* Navigation46aa22___actions_newList(void* ptr);
void* Navigation46aa22___dynamicPropertyNames_atList(void* ptr, int i);
void Navigation46aa22___dynamicPropertyNames_setList(void* ptr, void* i);
void* Navigation46aa22___dynamicPropertyNames_newList(void* ptr);
void* Navigation46aa22___findChildren_atList2(void* ptr, int i);
void Navigation46aa22___findChildren_setList2(void* ptr, void* i);
void* Navigation46aa22___findChildren_newList2(void* ptr);
void* Navigation46aa22___findChildren_atList3(void* ptr, int i);
void Navigation46aa22___findChildren_setList3(void* ptr, void* i);
void* Navigation46aa22___findChildren_newList3(void* ptr);
void* Navigation46aa22___findChildren_atList(void* ptr, int i);
void Navigation46aa22___findChildren_setList(void* ptr, void* i);
void* Navigation46aa22___findChildren_newList(void* ptr);
void* Navigation46aa22___children_atList(void* ptr, int i);
void Navigation46aa22___children_setList(void* ptr, void* i);
void* Navigation46aa22___children_newList(void* ptr);
void* Navigation46aa22_NewNavigation(void* parent, long long ff);
void Navigation46aa22_DestroyNavigation(void* ptr);
void Navigation46aa22_DestroyNavigationDefault(void* ptr);
char Navigation46aa22_CloseDefault(void* ptr);
char Navigation46aa22_EventDefault(void* ptr, void* event);
char Navigation46aa22_FocusNextPrevChildDefault(void* ptr, char next);
char Navigation46aa22_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void Navigation46aa22_ActionEventDefault(void* ptr, void* event);
void Navigation46aa22_ChangeEventDefault(void* ptr, void* event);
void Navigation46aa22_CloseEventDefault(void* ptr, void* event);
void Navigation46aa22_ContextMenuEventDefault(void* ptr, void* event);
void Navigation46aa22_DragEnterEventDefault(void* ptr, void* event);
void Navigation46aa22_DragLeaveEventDefault(void* ptr, void* event);
void Navigation46aa22_DragMoveEventDefault(void* ptr, void* event);
void Navigation46aa22_DropEventDefault(void* ptr, void* event);
void Navigation46aa22_EnterEventDefault(void* ptr, void* event);
void Navigation46aa22_FocusInEventDefault(void* ptr, void* event);
void Navigation46aa22_FocusOutEventDefault(void* ptr, void* event);
void Navigation46aa22_HideDefault(void* ptr);
void Navigation46aa22_HideEventDefault(void* ptr, void* event);
void Navigation46aa22_InputMethodEventDefault(void* ptr, void* event);
void Navigation46aa22_KeyPressEventDefault(void* ptr, void* event);
void Navigation46aa22_KeyReleaseEventDefault(void* ptr, void* event);
void Navigation46aa22_LeaveEventDefault(void* ptr, void* event);
void Navigation46aa22_LowerDefault(void* ptr);
void Navigation46aa22_MouseDoubleClickEventDefault(void* ptr, void* event);
void Navigation46aa22_MouseMoveEventDefault(void* ptr, void* event);
void Navigation46aa22_MousePressEventDefault(void* ptr, void* event);
void Navigation46aa22_MouseReleaseEventDefault(void* ptr, void* event);
void Navigation46aa22_MoveEventDefault(void* ptr, void* event);
void Navigation46aa22_PaintEventDefault(void* ptr, void* event);
void Navigation46aa22_RaiseDefault(void* ptr);
void Navigation46aa22_RepaintDefault(void* ptr);
void Navigation46aa22_ResizeEventDefault(void* ptr, void* event);
void Navigation46aa22_SetDisabledDefault(void* ptr, char disable);
void Navigation46aa22_SetEnabledDefault(void* ptr, char vbo);
void Navigation46aa22_SetFocus2Default(void* ptr);
void Navigation46aa22_SetHiddenDefault(void* ptr, char hidden);
void Navigation46aa22_SetStyleSheetDefault(void* ptr, struct Moc_PackedString styleSheet);
void Navigation46aa22_SetVisibleDefault(void* ptr, char visible);
void Navigation46aa22_SetWindowModifiedDefault(void* ptr, char vbo);
void Navigation46aa22_SetWindowTitleDefault(void* ptr, struct Moc_PackedString vqs);
void Navigation46aa22_ShowDefault(void* ptr);
void Navigation46aa22_ShowEventDefault(void* ptr, void* event);
void Navigation46aa22_ShowFullScreenDefault(void* ptr);
void Navigation46aa22_ShowMaximizedDefault(void* ptr);
void Navigation46aa22_ShowMinimizedDefault(void* ptr);
void Navigation46aa22_ShowNormalDefault(void* ptr);
void Navigation46aa22_TabletEventDefault(void* ptr, void* event);
void Navigation46aa22_UpdateDefault(void* ptr);
void Navigation46aa22_UpdateMicroFocusDefault(void* ptr);
void Navigation46aa22_WheelEventDefault(void* ptr, void* event);
void* Navigation46aa22_PaintEngineDefault(void* ptr);
void* Navigation46aa22_MinimumSizeHintDefault(void* ptr);
void* Navigation46aa22_SizeHintDefault(void* ptr);
void* Navigation46aa22_InputMethodQueryDefault(void* ptr, long long query);
char Navigation46aa22_HasHeightForWidthDefault(void* ptr);
;
int Navigation46aa22_HeightForWidthDefault(void* ptr, int w);
int Navigation46aa22_MetricDefault(void* ptr, long long m);
void Navigation46aa22_InitPainterDefault(void* ptr, void* painter);
char Navigation46aa22_EventFilterDefault(void* ptr, void* watched, void* event);
void Navigation46aa22_ChildEventDefault(void* ptr, void* event);
void Navigation46aa22_ConnectNotifyDefault(void* ptr, void* sign);
void Navigation46aa22_CustomEventDefault(void* ptr, void* event);
void Navigation46aa22_DeleteLaterDefault(void* ptr);
void Navigation46aa22_DisconnectNotifyDefault(void* ptr, void* sign);
void Navigation46aa22_TimerEventDefault(void* ptr, void* event);

#ifdef __cplusplus
}
#endif

#endif